### PR TITLE
My emberjs calculator

### PR DESCRIPTION
**Pull request by dumbtroll**
Here it is

### CODE REVIEW

**Comment by anshumanv** [comment]
Thanks, looks good, but please can you provide a link where we can test it to get work done quickly?

Cheers!

**Comment by djmgit** [comment]
@anshumanv https://dumbtroll.github.io/calc.html, check this link :)

**Comment by anshumanv** [comment]
How did you get it @djmgit ?

**Comment by djmgit** [comment]
@anshumanv from here : https://codein.withgoogle.com/dashboard/task-instances/5902180823334912/?sp-page=2 :P

**Comment by anshumanv** [comment]
Ah, thanks @djmgit :smile: 
I think this can be merged, only 14hrs left for task completion and besides the calculator is functional.

**Comment by djmgit** [comment]
@anshumanv yes, the app is functional, README.md has all instructions and PR looks good. This can be approved.

**Comment by anshumanv** [comment]
Please approve and merge @djmgit when you feel things are in place. :smile: 
Nicely Done @dumbtroll :+1:

**Comment by anshumanv** [comment]
Merging.

**Comment by anshumanv** [comment]
@dumbtroll ideally you should request only one commit to be merged, please learn how to squash commits and do so from next time on. 

Cheers! :smile:

**Pull request merged**
