### PR TITLE
Simple Ember Js App

### PR DESCRIPTION
**Pull request by naveentherocker**
Simple Ember.js App

### CODE REVIEW

**Comment by naveentherocker** [comment]
http://naveenrocker.tk/emberjs-app/

**Comment by djmgit** [comment]
@naveentherocker great :+1: nice work
Just a last thing. Please provide a proper commit description rather than just '1'.
Also please provide a README.md file telling how to build and run the app. So that others can also learn from your app. Some inline comments would be great :)

**Comment by naveentherocker** [comment]
Sorry for the Improper Description @djmgit . So Do you need an explanation on how the App Works or How to use the App?

**Comment by djmgit** [comment]
@naveentherocker Just a proper Documentation of the app. Please refer to any open source project on github and you can find what an usual README.md file contains.
Here is an overview
- What is the project all about
- How it works/ how to use it
- tech stack used
- Why did you build it? (As a part of GCI, sounds cool right ;)
- How to build it locally and test it if a new comer wants to use it locally and contribute to it.

Hope that helps 
Nice work by the way :)

**Comment by naveentherocker** [comment]
Sure. I'll make it ready soon

**Comment by naveentherocker** [comment]
Done

**Comment by djmgit** [comment]
@naveentherocker great! Congo for completing the task :+1: 

Some suggestions to take this project forward:
- After the user presses on a operator, do not make the existing expression (digit) disappear, rather append the operator and the next entered digit to the existing expression and display the entire expression on screen. This will improve UX.
- Add an option to delete the last entered operand/operator

Nice work, happy open sourcing :+1:  :)

**Comment by naveentherocker** [comment]
Sure Thank You @djmgit

**Pull request closed without merging**
